openapi: 3.0.3
info:
  title: Product APIs
  description: These APIs are for handling product module.
  version: 1.0.0
paths:
  /products:
    post:
      operationId: addProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
          description: Product added succesfully
        403:
          description: Bad input
    get:
      operationId: getProducts
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponseList'
          description: Get all products succesfully
components:
  schemas:
    ProductRequest:
      type: object
      properties:
        name:
          type: string

    ProductResponseList:
      type: array
      items:
        $ref: '#/components/schemas/ProductResponse'
    ProductResponse:
      type: object
      properties:
        name:
          type: string